import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body>
        <SidebarProvider>
          <AppSidebar />
          <SidebarTrigger />
          <main className="mb-4 rounded-xl p-4 w-full">{children}</main>
        </SidebarProvider>
      </body>
    </html>
  );
}
